import assets from '../work/assets.js';
import seed from '../data/catalog-seed.json';
import events from '../data/events.json';
import reports from '../data/reports-index.json';
import {normalize,mergeLocalizedData,checkReferences,kinds,cleanText,safeURL,fail,now,id} from './model.js';
const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const query=(env,sql,...args)=>env.DB.prepare(sql).bind(...args);
const rows=async(env,sql,...args)=>(await query(env,sql,...args).all()).results;
const unpack=e=>({...e,data:JSON.parse(e.data)});
async function serveFile(env,a){let f=await env.BUCKET.get(a.id);if(!f)fail('附件暂时不可用。',404);return new Response(f.body,{headers:{'content-type':a.mime,'content-disposition':`attachment; filename*=UTF-8''${encodeURIComponent(a.name)}`,'cache-control':'private, no-store','x-content-type-options':'nosniff'}})}
async function catalog(env){const db=await rows(env,'SELECT * FROM entities WHERE version > 0');const merged=new Map(seed.map(e=>[e.id,e]));for(const e of db)merged.set(e.id,unpack(e));return [...merged.values()]}
async function member(req,env){if(!env.OWNER_EMAIL)fail('共建管理员尚未启用。站点所有者确认管理员邮箱后即可开放投稿。',503);const auth=req.headers.get('oai-authenticated-user-id');const email=(req.headers.get('oai-authenticated-user-email')||'').trim().toLowerCase();if(!auth||!email)fail('请先登录后参与共建。',401);let name=email;try{if(req.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8')name=decodeURIComponent(req.headers.get('oai-authenticated-user-full-name')||'')||email}catch{}
 if(env.OWNER_EMAIL&&email===env.OWNER_EMAIL.trim().toLowerCase())await query(env,"INSERT OR IGNORE INTO members (id,auth_id,email,name,role,status,created) VALUES (?,?,?,?, 'admin','active',?)",'site-owner',auth,email,cleanText(name),now()).run();
 await query(env,"UPDATE members SET auth_id=?,status='active',name=? WHERE email=? AND auth_id IS NULL AND status='invited'",auth,cleanText(name),email).run();
 const m=await query(env,'SELECT * FROM members WHERE auth_id=?',auth).first();if(!m||m.status!=='active')fail('你的账号尚未获准参与共建，请联系站点管理员。',403);return m;
}
function role(m,allowed){if(!allowed.includes(m.role))fail('此操作需要审核员或管理员权限。',403)}
async function body(req){if(!(req.headers.get('content-type')||'').includes('application/json'))fail('请求格式不正确。');const raw=await req.text();if(raw.length>1024*1024)fail('提交内容过大。',413);try{return JSON.parse(raw)}catch{fail('请求内容无法读取。')}}
async function verifyFiles(env,d,m){for(const fid of d.attachments||[]){const a=await query(env,'SELECT * FROM attachments WHERE id=?',fid).first();if(!a||(a.owner!==m.id&&!a.published))fail('附件不存在或不属于当前投稿者。')}}
function duplicates(d,kind,cat,exclude){return cat.filter(e=>e.kind===kind&&e.id!==exclude&&[e.data.name,e.data.en,...(e.data.aliases||[])].some(n=>n&&[d.name,d.en,...d.aliases].some(v=>v&&v.normalize('NFKC').toLowerCase()===n.normalize('NFKC').toLowerCase()))).map(e=>({id:e.id,name:e.name}))}
async function newSubmission(env,m,b){let cat=await catalog(env),existing=b.entityId?cat.find(e=>e.id===b.entityId):null;if(b.entityId&&!existing)fail('原条目不存在。',404);if(existing&&existing.kind!==b.kind)fail('不能更改条目类型。');if(existing&&b.baseVersion!=null&&b.baseVersion!==existing.version)fail('原条目已有更新，请重新载入后提交。',409);let status=b.submit?'pending':'draft';let d=normalize(mergeLocalizedData(existing?.data||{},b.data),b.kind,b.submit);checkReferences(d,b.kind,cat);await verifyFiles(env,d,m);const key=cleanText(b.requestKey,100);if(!key)fail('缺少提交编号，请重试。');let prior=await query(env,'SELECT * FROM submissions WHERE author=? AND request_key=?',m.id,key).first();if(prior)return unpack(prior);let sid=id(),eid=existing?.id||id(),t=now();await query(env,'INSERT INTO submissions (id,entity_id,kind,data,base_version,revision,status,author,request_key,created,updated) VALUES (?,?,?,?,?,1,?,?,?,?,?)',sid,eid,b.kind,JSON.stringify(d),existing?.version||0,status,m.id,key,t,t).run();return {id:sid,entity_id:eid,kind:b.kind,data:d,base_version:existing?.version||0,revision:1,status,author:m.id,duplicates:duplicates(d,b.kind,cat,eid)};
}
async function decide(env,m,sid,b){role(m,['admin','reviewer']);const s=await query(env,'SELECT * FROM submissions WHERE id=?',sid).first();if(!s)fail('投稿不存在。',404);if(s.status!=='pending'||s.revision!==b.revision)fail('投稿已变更，请刷新后重新核对。',409);if(s.author===m.id&&!(m.role==='admin'&&b.ownerPublish===true&&cleanText(b.reason)))fail('不能审核自己的投稿；管理员需明确选择自行发布并填写理由。',403);let reason=cleanText(b.reason,1000);if(b.action==='return'){if(!reason)fail('请填写需要补充的内容。');let r=await query(env,"UPDATE submissions SET status='returned',reason=?,reviewer=?,revision=revision+1,updated=? WHERE id=? AND revision=? AND status='pending'",reason,m.id,now(),sid,b.revision).run();if(!r.meta.changes)fail('投稿已变更。',409);return {ok:true}}
 if(b.action!=='approve')fail('未知的审核操作。');let cat=await catalog(env);const baseline=cat.find(e=>e.id===s.entity_id);let d=normalize(mergeLocalizedData(baseline?.data||{},JSON.parse(s.data)),s.kind,true);checkReferences(d,s.kind,cat);if((baseline?.version||0)!==s.base_version)fail('原条目已有新版本，请退回投稿并基于最新资料重新修改。',409);
 const token=id(),t=now(),action=s.author===m.id?'管理员自行发布':'审核通过';let cmds=[];
 cmds.push(query(env,'INSERT OR IGNORE INTO entities (id,kind,name,data,version,updated) VALUES (?,?,?,?,?,?)',s.entity_id,s.kind,baseline?.name||d.name,JSON.stringify(baseline?.data||{}),baseline?.version||0,t));
 if(baseline)cmds.push(query(env,'INSERT OR IGNORE INTO history (id,entity_id,version,data,actor,action,created) VALUES (?,?,?,?,?,?,?)',id(),s.entity_id,baseline.version,JSON.stringify(baseline.data),'初始资料整理','初始版本',baseline.updated));
 cmds.push(query(env,"UPDATE submissions SET status='approving',token=?,reviewer=?,reason=? WHERE id=? AND status='pending' AND revision=? AND base_version=(SELECT version FROM entities WHERE id=entity_id)",token,m.id,reason,sid,b.revision));
 cmds.push(query(env,"UPDATE entities SET name=?,data=?,version=version+1,updated=?,submission_id=? WHERE id=? AND EXISTS (SELECT 1 FROM submissions WHERE id=? AND status='approving' AND token=?)",d.name,JSON.stringify(d),t,sid,s.entity_id,sid,token));
 cmds.push(query(env,'INSERT INTO history (id,entity_id,version,data,actor,action,reason,created) SELECT ?,id,version,data,?,?,?,? FROM entities WHERE id=? AND submission_id=? AND EXISTS (SELECT 1 FROM submissions WHERE id=? AND token=?)',id(),m.name,action,reason,t,s.entity_id,sid,sid,token));
 for(const fid of d.attachments)cmds.push(query(env,'UPDATE attachments SET published=1 WHERE id=? AND EXISTS (SELECT 1 FROM submissions WHERE id=? AND token=?)',fid,sid,token));
 cmds.push(query(env,"UPDATE submissions SET status='approved',revision=revision+1,updated=? WHERE id=? AND status='approving' AND token=?",t,sid,token));
 await env.DB.batch(cmds);const final=await query(env,'SELECT status,token FROM submissions WHERE id=?',sid).first();if(final.token!==token||final.status!=='approved')fail('资料刚刚发生变化，本次未发布，请刷新核对。',409);return {ok:true,entityId:s.entity_id};
}
async function imports(env,m,b,commit){if(!Array.isArray(b.rows)||!b.rows.length||b.rows.length>100)fail('每批支持1至100行。');const cat=await catalog(env);let preview=[],seen=new Set();for(let i=0;i<b.rows.length;i++){const r=b.rows[i];try{const old=r.entityId?cat.find(e=>e.id===r.entityId):null;if(r.entityId&&!old)fail('条目编号不存在');if(old&&old.kind!==r.kind)fail('条目类型不一致');if(r.entityId&&seen.has(r.entityId))fail('同一批不能重复修改同一条目');seen.add(r.entityId||id());const nonempty=Object.fromEntries(Object.entries(r.data||{}).filter(([k,v])=>v!==''&&v!==null&&v!==undefined&&(!Array.isArray(v)||v.length)));const d=normalize(mergeLocalizedData(old?.data||{},{...old?.data,...nonempty}),r.kind,true);checkReferences(d,r.kind,cat);await verifyFiles(env,d,m);let same=old&&JSON.stringify(normalize(old.data,r.kind,true))===JSON.stringify(d);preview.push({row:i+2,kind:r.kind,entityId:old?.id||null,baseVersion:old?.version||0,data:d,status:same?'unchanged':old?'update':'new',duplicates:duplicates(d,r.kind,cat,old?.id)});}catch(e){preview.push({row:i+2,status:'error',message:e.message})}}
 if(!commit)return {rows:preview};if(preview.some(r=>r.status==='error'))fail('请修正所有错误后再提交；尚未导入任何条目。');const key=cleanText(b.importKey,80);if(!key)fail('缺少批次编号。');let t=now(),cmds=[];for(const p of preview.filter(p=>p.status!=='unchanged'))cmds.push(query(env,"INSERT OR IGNORE INTO submissions (id,entity_id,kind,data,base_version,revision,status,author,request_key,created,updated) VALUES (?,?,?,?,?,1,'pending',?,?,?,?)",id(),p.entityId||id(),p.kind,JSON.stringify(p.data),p.baseVersion,m.id,key+':'+p.row,t,t));let results=cmds.length?await env.DB.batch(cmds):[];return {ok:true,submitted:results.reduce((a,r)=>a+r.meta.changes,0),unchanged:preview.filter(p=>p.status==='unchanged').length};
}
export default {async fetch(req,env){try{const url=new URL(req.url),p=url.pathname;if(!p.startsWith('/api/')){let path=p==='/'?'/index.html':p==='/reports'?'/reports.html':['/community','/catalog'].includes(p)?'/community.html':p;const a=assets[path];if(!a)return new Response('未找到此页面',{status:404});const bytes=Uint8Array.from(atob(a.body),c=>c.charCodeAt(0));return new Response(req.method==='HEAD'?null:bytes,{headers:{'content-type':a.type,'cache-control':/html|javascript|css/.test(a.type)?'no-cache':'public, max-age=3600','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin'}})}
 if(req.method!=='GET'&&req.method!=='HEAD'){if(req.headers.get('origin')!==url.origin)fail('请从本网站提交操作。',403)}
 if(p==='/api/events'&&req.method==='GET'){const approved=(await catalog(env)).filter(e=>e.kind==='event').map(e=>({id:e.id,title:e.data.name,summary:e.data.notes,type:e.data.eventType,startDate:e.data.startDate,endDate:e.data.endDate||null,publishedDate:e.data.publishedDate||null,dateNote:e.data.dateNote,country:e.data.country,region:e.data.regionId,lat:e.data.lat,lng:e.data.lng,precision:e.data.locationPrecision,sourceName:e.data.sourceTitle,sourceURL:e.data.sourceURL,verification:'社区投稿已审核',checkedDate:e.updated.slice(0,10)}));return json({...events,events:[...events.events,...approved]})}
 if(p==='/api/catalog'&&req.method==='GET')return json({entities:await catalog(env)});
 if(p==='/api/reports'&&req.method==='GET')return json({reports});
 if(p.startsWith('/api/history/')&&req.method==='GET'){let eid=decodeURIComponent(p.slice(13)),h=await rows(env,'SELECT * FROM history WHERE entity_id=? ORDER BY version DESC',eid);if(!h.length){const s=seed.find(e=>e.id===eid);if(s)h=[{entity_id:eid,version:s.version,data:JSON.stringify(s.data),actor:s.origin,action:'初始版本',created:s.updated}]}return json({history:h.map(unpack)})}
 if(p.startsWith('/api/attachments/')&&req.method==='GET'){const a=await query(env,'SELECT * FROM attachments WHERE id=?',p.slice(17)).first();if(a?.published)return serveFile(env,a)}
 const m=await member(req,env);
 if(p==='/api/me')return json({member:{id:m.id,name:m.name,email:m.email,role:m.role},sitePrivate:true});
 if(p==='/api/members'){role(m,['admin']);if(req.method==='GET')return json({members:await rows(env,'SELECT id,name,email,role,status,created FROM members ORDER BY created')});if(req.method==='POST'){const b=await body(req),email=cleanText(b.email).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail('请填写有效邮箱。');if(!['member','reviewer'].includes(b.role))fail('邀请角色不正确。');if(email===m.email)fail('当前管理员已在成员列表。');const existing=await query(env,'SELECT * FROM members WHERE email=?',email).first();if(existing)fail('该邮箱已在成员列表，可直接修改其角色。',409);await query(env,"INSERT INTO members (id,email,name,role,status,created) VALUES (?,?,?,?,'invited',?)",id(),email,email,b.role,now()).run();return json({ok:true,note:'共建资格已登记。站点管理员仍需在分享设置中授予该邮箱网站访问权限，再复制邀请链接给对方。'})}}
 if(p.startsWith('/api/members/')&&req.method==='PATCH'){role(m,['admin']);let mid=p.slice(13),b=await body(req);if(mid===m.id||mid==='site-owner')fail('不能修改站点所有者的权限。');if(!['member','reviewer'].includes(b.role)||!['active','suspended','invited'].includes(b.status))fail('角色或状态不正确。');const old=await query(env,'SELECT * FROM members WHERE id=?',mid).first();if(!old)fail('成员不存在。',404);const status=old.auth_id?(b.status==='invited'?'active':b.status):(b.status==='suspended'?'suspended':'invited');await env.DB.batch([query(env,'UPDATE members SET role=?,status=? WHERE id=?',b.role,status,mid),query(env,'INSERT INTO audit (id,target,actor,action,detail,created) VALUES (?,?,?,?,?,?)',id(),mid,m.name,'成员权限调整',JSON.stringify({before:{role:old.role,status:old.status},after:{role:b.role,status}}),now())]);return json({ok:true})}
 if(p==='/api/submissions'){if(req.method==='GET'){let list=await rows(env,'SELECT s.*,m.name AS author_name FROM submissions s JOIN members m ON m.id=s.author WHERE author=? ORDER BY updated DESC LIMIT 200',m.id);return json({submissions:list.map(unpack)})}if(req.method==='POST')return json(await newSubmission(env,m,await body(req)),201)}
 if(p==='/api/review'&&req.method==='GET'){role(m,['admin','reviewer']);return json({submissions:(await rows(env,"SELECT s.*,m.name AS author_name FROM submissions s JOIN members m ON m.id=s.author WHERE s.status='pending' ORDER BY s.updated",)).map(unpack)})}
 const submatch=p.match(/^\/api\/submissions\/([^/]+)(\/decision)?$/);if(submatch){let sid=submatch[1];if(submatch[2]&&req.method==='POST')return json(await decide(env,m,sid,await body(req)));const s=await query(env,'SELECT * FROM submissions WHERE id=?',sid).first();if(!s)fail('投稿不存在。',404);if(s.author!==m.id&&!['admin','reviewer'].includes(m.role))fail('不能查看其他成员的投稿。',403);if(req.method==='GET')return json(unpack(s));if(req.method==='PATCH'){if(s.author!==m.id)fail('只有投稿者可以修改。',403);const b=await body(req);if(s.revision!==b.revision||!['draft','returned','pending'].includes(s.status))fail('投稿状态已变化，请重新载入。',409);if(b.withdraw){let r=await query(env,"UPDATE submissions SET status='withdrawn',revision=revision+1,updated=? WHERE id=? AND revision=? AND status IN ('draft','returned','pending')",now(),sid,b.revision).run();if(!r.meta.changes)fail('投稿已变更。',409);return json({ok:true})}const cat=await catalog(env),current=cat.find(e=>e.id===s.entity_id);const preserved=mergeLocalizedData(current?.data||{},JSON.parse(s.data));const d=normalize(mergeLocalizedData(preserved,b.data),s.kind,!!b.submit);checkReferences(d,s.kind,cat);await verifyFiles(env,d,m);const base=cat.find(e=>e.id===s.entity_id)?.version||0;if(b.baseVersion!==base)fail('原条目已有更新，请重新载入后合并修改。',409);let r=await query(env,"UPDATE submissions SET data=?,base_version=?,status=?,revision=revision+1,updated=? WHERE id=? AND revision=? AND status IN ('draft','returned','pending')",JSON.stringify(d),base,b.submit?'pending':'draft',now(),sid,b.revision).run();if(!r.meta.changes)fail('投稿已变更。',409);return json({ok:true,revision:s.revision+1})}}
 if(p==='/api/imports/preview'&&req.method==='POST')return json(await imports(env,m,await body(req),false));if(p==='/api/imports/submit'&&req.method==='POST')return json(await imports(env,m,await body(req),true));
 if(p==='/api/attachments'&&req.method==='POST'){if(Number(req.headers.get('content-length'))>10*1024*1024)fail('附件不能超过10MB。',413);const file=await req.arrayBuffer();if(file.byteLength>10*1024*1024||file.byteLength<12)fail('附件大小不符合要求。');const v=new Uint8Array(file),sig=Array.from(v.slice(0,4)).join(','),ascii=new TextDecoder().decode(v.slice(0,12));let mime=sig==='137,80,78,71'?'image/png':v[0]===255&&v[1]===216?'image/jpeg':ascii.startsWith('%PDF-')?'application/pdf':ascii.startsWith('RIFF')&&ascii.slice(8,12)==='WEBP'?'image/webp':null;if(!mime)fail('仅支持 JPG、PNG、WebP 图片或 PDF。');let fid=id(),name=cleanText(decodeURIComponent(req.headers.get('x-file-name')||'证明文件'));await env.BUCKET.put(fid,file,{httpMetadata:{contentType:mime}});try{await query(env,'INSERT INTO attachments (id,owner,name,mime,size,created,published) VALUES (?,?,?,?,?,?,0)',fid,m.id,name,mime,file.byteLength,now()).run()}catch(e){await env.BUCKET.delete(fid);throw e}return json({id:fid,name,mime,size:file.byteLength},201)}
 if(p.startsWith('/api/attachments/')&&req.method==='GET'){const fid=p.slice(17),a=await query(env,'SELECT * FROM attachments WHERE id=?',fid).first();if(!a||(!a.published&&a.owner!==m.id&&!['admin','reviewer'].includes(m.role)))fail('附件不存在或无权查看。',404);let f=await env.BUCKET.get(fid);if(!f)fail('附件暂时不可用。',404);return new Response(f.body,{headers:{'content-type':a.mime,'content-disposition':`attachment; filename*=UTF-8''${encodeURIComponent(a.name)}`,'cache-control':'private, no-store','x-content-type-options':'nosniff'}})}
 return json({error:'未找到此操作。'},404);
 }catch(e){if(!e.status)console.error('Request failed',e.message);return json({error:e.status?e.message:'资料服务暂时不可用，请稍后重试。你的输入仍保留在页面。'},e.status||503)}}};
